# 에러 핸들링
* 에러가 발생하면 프로그램이 종료되기때문에 처리가 필요함
## 처리 방법
1. try ... catch
```js
console.log('에러 발생 전');

// 에러 발생 여지가 있는 부분
try {
  (3).split('');
  
} catch (e) {  // 에러 발생시 종료되지 않고 이곳으로 핸들링
  console.error('🛑 에러!!', e);
}

console.log('에러 발생 후');
```
2. try ... cath ... finally
* `try`문이 성공하든 실패하든 `finally`문은 무조건 실행
* 소켓 연결 해제와 같은 곳에서 사용
```js
function connect () { console.log('☀️', '통신 연결'); }
function disconnect () { console.log('🌙', '통신 연결 해제'); }
function sendArray (arr) { console.log('전송', arr); }

function sendStringAsArray (str) {
  connect();

  try {
    sendArray(str.split(''));
    return true;

  } catch (e) {
    console.error('🛑 에러!!', e);
    return false;

  } finally {
    // 전송 성공 여부와 관계없이 연결은 끊어야 함 (무조건 실행)
    disconnect();
    console.log('- - - - - - - -');
  }

['ABC', '가나다', 123, '123'].forEach(i => {
  console.log(
    sendStringAsArray(i) 
    ? '[성공]' : '[실패]', '\n\n'
  );
});
```
## Error 객체
* 에러 발생 시 던져지는 객체
* 에러에 대한 정보를 담으며 커스텀 가능
```js
// 두 번째 인자로 이유를 명시할 수도 있음
const error = new Error(
  '뭔가 잘못됐어',
  { cause: '뭘 잘못했으니까' }
);
console.log(error.name);
console.log(error.message);
// cause를 입력했을 경우
console.log(error.cause);
```
* 에러 발생 방법
```js
throw new Error('이유를 묻지 마라');
```
### 에러 종류
* `SyntaxError` - 문법에 이상이 있을 때
* `TypeError` - 주어진 명령에 적절한 자료형이 아닐 때
* `ReferenceError` - 잘못된 값을 참조했을 때
* `RangeError` - 유효한 범위를 벗어나는 숫자가 사용되었을 때
* 오류 종류에 따른 대처
```js
errorFuncs.forEach(func => {
  try {
    func();

  } catch (e) {
    if (e instanceof TypeError) {
      console.error('자료형 확인하세요.');
      return;
    }
    if (e instanceof ReferenceError) {
      console.error('선언 안 된 거 쓴 거 없는지 확인하세요.');
      return;
    }
    console.error('아니, 뭘 한 거에요?');
  }
});
```
* 종류에 따라 직접 에러 생성
```js
// 특정 월의 당번으로 지원하는 함수
function applyForMonth (date) {
  try {
    if (typeof date !== 'number') {
      throw new TypeError('숫자로 입력해주세요.');
    }
    if (date < 1 || date > 12) {
      throw new RangeError('유효한 월을 입력해주세요.');
    }

    console.log(`${date}월 당번으로 등록되셨습니다.`);

  } catch (e) {
    console.error('🛑 에러 발생!', e);
    console.log('다시 등록해주세요.');
  }
}
```
### 커스텀 에러 만들기
* Error 객체를 상속받아 생성
* 부모 객체의 `name`과 `message` 프로퍼티를 재정의

### 에러 버블링
* 함수가 중첩되어있을 때 에러를 핸들링하는 코드가 있는 함수까지 전달됨
* 에러는 발생한 곳 가까이서 처리하는 것이 좋음
```js
function func1 () {
  throw new Error('에러');
}

function func2 () {
  func1();
}

function func3 () {
  func2();
}

function func4 () {
  try {
    func3();

  } catch (e) {
    console.error(e);
  }
  console.log('실행완료');
}

func4();
```
# var 지양 이유
* `var`은 `let`과 `const`가 생기기 전 변수 선언에 사용되던 문
* 각종 문제점이 있어 오늘날은 사용 지양
## 특징
1. 선언 없이 사용 가능
2. 재선언 가능
3. 블록 레벨 스코프 무시
* 함수 레벨의 스코프는 유지
4. 호이스팅
* 호이스팅시 오류 대신 undefined 반환

# 엄격 모드 (strict mode)
* 문제 유발 가능성 있는 코드를 검사하는 모드
* 문서 최상단에 작성하여 적용
```js
// 선언되지 않은 변수 사용 금지
'use strict'; // 쌍따옴표도 가능

notDeclared = 1; // 오류 발생!
```
* 함수 최상단에 작성할 경우 해당 함수만 적용
```js
notDec1 = 1;

function strictFunc () {
'use strict';

 notDec2 = 2;
 console.log(notDec2);
}

console.log(notDec1);
strictFunc();
```
## 예시
1. 선언되지 않은 변수 사용시 오류 밤생
```js
'use strict';
x = 1;
console.log(x); // 오류 발생
```
2. 변수, 함수, 인자 등 삭제불가한 것을 삭제시 오류 발생
```js
'use strict';

let toDelete2 = 1;
delete toDelete2;  // 오류 발생
```
3. 인자명 중복시 오류 발생
```js
// 'use strict';

function add(x, x) {
  return x + x;
}

console.log(add(1, 2));  // 오류 발생
```